### ISSUE TITLE
iCELink not found

### ISSUE THREAD

**Issue by yoyeung** [wuxx/icesugar#2]
When i try to "make prog_flash" it cannot find the path... look like iceLink removed from the repro?

**Comment by wuxx** [comment]
which example you are testing ?
you can also use 
$icesprog xxx.bin
 to program the bitstream.

**Comment by yoyeung** [comment]
Thanks for the reply, but i got this issue in mac.
Can't find iCE FTDI USB device (vendor_id 0x0403, device_id 0x6010 or 0x6014).
So that should I use type C port or another one?
Thanks

**Comment by wuxx** [comment]
icesprog = icesugar program
not iceprog

**Comment by yoyeung** [comment]
![image](https://user-images.githubusercontent.com/451538/86527170-f9b2b380-bece-11ea-944d-4d6ea421dbf2.png)

**Comment by wuxx** [comment]
it's icesprog, not iceprog, notice the 's'

**Comment by yoyeung** [comment]
![image](https://user-images.githubusercontent.com/451538/86527257-cd4b6700-becf-11ea-84b6-e36ece30746c.png)
I should install some lib or?

**Comment by yoyeung** [comment]
Oops...i got u...

**Comment by wuxx** [comment]
the binary is at
https://github.com/wuxx/icesugar/tree/master/tools/
it depends libusb & hidapi

**Comment by yoyeung** [comment]
thx
