### ISSUE TITLE
Is this board compatible to the Lattice Diamond?

### ISSUE THREAD

**Issue by ms0488638** [wuxx/icesugar#27]
Hi,

Is this board compatible to the Lattice Diamond?

Most of your tutorial are based on open source tools, I wonder if this board can work with Lattice Diamond.

Thanks

**Comment by wuxx** [comment]
you can code with Lattice's official IDE, program with drag and drop.
the on-board programmer is not supported by the Lattice IDE (like Diamond, icecube)
