### ISSUE TITLE
What use really has the jumper J1?

### ISSUE THREAD

**Issue by juanmard** [wuxx/icesugar#29]
Pin 35 from FPGA is an output from internal PLL (ICE_CLK), so is an input on microcontroller STM32 (as a clock?).
Why need a jumper here? What is it used for?

![imagen](https://user-images.githubusercontent.com/17770252/122139857-2f377f00-ce4a-11eb-84bd-4693b99af993.png)

**Comment by wuxx** [comment]
the MCU output 12MHz clock to iCE40 as external clock, but if you need other frequence, you can take off the jumper and connect your specified clock source.

**Comment by juanmard** [comment]
Thanks!
