### ISSUE TITLE
Get or set data from SPI flash.

### ISSUE THREAD

**Issue by juanmard** [wuxx/icesugar#31]
How do I get or set arbitrary binary data to the SPI flash through the _iCELink_ (either drag and drop or icesprog)?

**Comment by wuxx** [comment]
for example
`
/* write image to flash */
$icesprog -w flash.bin

/* read 1024 Bytes from flash, default by offset 0 */
$icesprog -r -l 1024 out.bin
/* read 1024 Bytes from flash, by offset 1M */
$icesprog -r -o 0x100000 -l 1024 out.bin

`

**Comment by juanmard** [comment]
Perfect! Thanks!
