### ISSUE TITLE
Support for Lattice downloader environment

### ISSUE THREAD

**Issue by lanczki** [wuxx/icesugar#32]
It would be greate if the board could support the Lattice environment in a newer version.

What I'd like to propose is the following. 
The board should include a header where the iCE40 SPI pins and the CRESET_B pin are routed out.
![image](https://user-images.githubusercontent.com/69252056/122637883-4b107e80-d0f1-11eb-87f4-d35219905942.png)
![image](https://user-images.githubusercontent.com/69252056/122637210-aa6c8f80-d0ed-11eb-902b-aabe18caf68b.png)

Or just the CRESET_B,ICE_SS,ICE_SCK should need a header because the ICE_MOSI and ICE_MISO are already routed out to J3 
![image](https://user-images.githubusercontent.com/69252056/122638053-2cf74e00-d0f2-11eb-86f1-b143adc37100.png)

**Comment by wuxx** [comment]
OK, will consider it later, thanks for you good advice~!

**Comment by lanczki** [comment]
Thanks :) Keep up the good work.
