### ISSUE TITLE
Part number / datasheet for 0.96" LCD?

### ISSUE THREAD

**Issue by cHemingway** [wuxx/icesugar#33]
On the [PMOD LCD 0.96" schematic](https://github.com/wuxx/icesugar/blob/master/schematic/pmod_lcd-0.96-v1.0.pdf) the LCD is just listed as "TFTLCD_0.96_SPI". 

Do you have a part number or datasheet for the LCD and LCD controller I can use to program for it?

**Comment by wuxx** [comment]
the 0.96 lcd is base on st7735s, with resolution 160x80, you can found datasheet and demo code in doc directory, just commit few minutes ago.

**Comment by cHemingway** [comment]
Thank you for your quick response! That datasheet looks good
