### ISSUE TITLE
advanced build feature request for IntelliJ IDEA 

### ISSUE THREAD

**Issue by fatalfeel** [wuxx/icesugar#37]
could add sbt build for IntelliJ IDEA 

https://github.com/wuxx/icesugar/tree/master/src/advanced

hope here can add chisel3 build for for IntelliJ IDEA

**Comment by hansfbaier** [comment]
You can't reasonably expect that from this project.
Your choice of IDE is your responsibility.
If you want something which has sbt integrated,
try Visual Studio code with the Metals Addon.

**Comment by fatalfeel** [comment]
IntelliJ IDEA - scala plugin already integrated sbt, like big project XiangShan risc-v
