### ISSUE TITLE
difference betwen icesprog and iceprog (from toolchain-ice40)

### ISSUE THREAD

**Issue by jemisa** [wuxx/icesugar#4]
Hi

do you plan to publish the source code of icesprog ?

And can you explain what's the difference between icesprog and iceprog  from https://github.com/YosysHQ/icestorm/tree/master/iceprog ?

**Comment by wuxx** [comment]
hello, 
currently the source is closed, maybe opensource in future.
icesprog = icesugar prog
this difference is 
iceprog use the ft2232 to program and icesprog use stm32f1 to program the spi-flash
