### ISSUE TITLE
Can this board run RISC-V

### ISSUE THREAD

**Issue by quantrpeter** [wuxx/icesugar#46]
Hi
  Can this board run RISC-V? Enough resources?
thanks

**Comment by hansfbaier** [comment]
Yes, it can. 
It even runs linux: https://github.com/smunaut/iCE40linux

**Comment by hansfbaier** [comment]
Although I would not recommend it for linux. Better use colorlight i5 for that.

**Comment by quantrpeter** [comment]
thank you, let me buy one
