### ISSUE TITLE
icesprog iCELink open fail

### ISSUE THREAD

**Issue by sirazenkov** [wuxx/icesugar#50]
I have an iCESugar-nano board with v1.1a iCELink firmware. Provided [icesprog](https://github.com/wuxx/icesugar/blob/master/tools/icesprog) binary isn't the latest one: it doesn't have clock select and gpio control features. Device programming works fine, but I also need these features.

I built both v1.1a and v1.1b icesprog binaries from sources, however, when I try to program the device, I get an output: iCELink open fail!

**Comment by wuxx** [comment]
hello, please try to add sudo before the command.

**Comment by taotieren** [comment]
https://github.com/wuxx/icesugar/tree/master/tools/src#install-60-icesugarrules
