### ISSUE TITLE
iceSugar v1.5 Clock @ 6MHz

### ISSUE THREAD

**Issue by ButterBison** [wuxx/icesugar#58]
I have just noticed that the ICE_CLK for my iceSugar v1.5 board is set at 6MHz. However the schematics indicate that the oscillator X1 is a 12MHz oscillator. 

The only thing I can see that can divide the cock is the icelink. 

I have tried with the iceprog tool as well to set the mco, but no luck.

```
$sudo ./icesprog -p
probe chip
board: [iCESugar]
flash: [w25q64] (8MB)
done

```

```
$ sudo ./icesprog -c 2
only iCESugar-Nano support mco select
^C
```

Can someone confirm this?

**Comment by wuxx** [comment]
Hello, iCESugar's clock is driven by iCELink's PA8, and the default should be 12MHz. How do you measure the 6MHz clock currently, with a logic analyzer or an oscilloscope?

**Comment by ButterBison** [comment]
Hi, 

Thanks for your reply. I just made a measurement with logic analyzer on the jumper J1.

![image](https://github.com/wuxx/icesugar/assets/56363693/95b7a3e6-ceb0-4c69-9c62-1b270b7e0757)
![image](https://github.com/wuxx/icesugar/assets/56363693/d3df6ac9-365d-488b-8829-22e8445f1806)


![image](https://github.com/wuxx/icesugar/assets/56363693/c6b5f349-8374-4f30-82c5-420797345183)
 
The clock is correct. I will need to double check my code. Closing this issue for now.
